# syntax=docker/dockerfile:1
# hadolint ignore=DL3006
FROM dock-core

ARG VERSION=dev
# Install Node.js LTS and npm
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs \
    npm \
 && rm -rf /var/lib/apt/lists/*

# Generate manifest
COPY scripts/manifest.sh /usr/local/bin/manifest.sh
RUN manifest.sh node "${VERSION}"
